import assert from "node:assert/strict";
import test from "node:test";

import { compileHierarchicalNetlist, compileNetlist } from "../lib/netlist";
import { importNetlistAsSchematic } from "../lib/netlistImport";
import { hierarchyCellViews } from "../lib/hierarchy";
import { createDemoDocument } from "../lib/schematic";
import { parseSchematicDocument } from "../lib/schematicValidation";

test("SPICE transistor netlist imports as a formal editable schematic", () => {
  const document = parseSchematicDocument(importNetlistAsSchematic(`
* SPEG generated inverter seed
.SUBCKT inv VIN VOUT VDD 0
M1 VOUT VIN 0 0 nmos W=1u L=45n M=2 NF=4
M2 VOUT VIN VDD VDD pmos W=2u L=45n M=2 NF=4
.ENDS inv
`, { project: "speg_import" }));

  assert.equal(document.cell, "inv");
  assert.equal(document.nodes.some((node) => node.kind === "netlabel" || node.kind === "junction"), false);
  assert.equal(document.nodes.filter((node) => node.kind === "nmos4").length, 1);
  assert.equal(document.nodes.filter((node) => node.kind === "pmos4").length, 1);
  assert.ok(document.netLabels.some((label) => label.text === "VIN"));
  assert.ok(document.netLabels.some((label) => label.text === "VOUT"));

  const compiled = compileNetlist(document, "spectre");
  assert.equal(compiled.issues.filter((issue) => issue.severity === "error").length, 0);
  assert.match(compiled.text, /^subckt inv VIN VOUT VDD 0$/m);
  assert.match(compiled.text, /^  M1 \(VOUT VIN 0 0\) nmos w=1u l=45n m=2 nf=4$/m);
  assert.match(compiled.text, /^  M2 \(VOUT VIN VDD VDD\) pmos w=2u l=45n m=2 nf=4$/m);
});

test("Spectre generated by Analog Studio can round-trip back to schematic", () => {
  const original = compileNetlist(createDemoDocument(), "spectre").text;
  const imported = parseSchematicDocument(importNetlistAsSchematic(original, { project: "roundtrip" }));
  const roundTrip = compileNetlist(imported, "spectre");

  assert.equal(roundTrip.issues.filter((issue) => issue.severity === "error").length, 0);
  assert.match(roundTrip.text, /^subckt cmos_inverter VIN VOUT$/m);
  assert.match(roundTrip.text, /^  M1 \(VOUT VIN 0 0\) nmos w=10u l=180n m=1 nf=1$/m);
  assert.match(roundTrip.text, /^  M2 \(VOUT VIN VDD VDD\) pmos w=20u l=180n m=1 nf=1$/m);
});

test("SPEG-style Spectre devices import with sources, passives, ports, and metadata", () => {
  const document = parseSchematicDocument(importNetlistAsSchematic(`
simulator lang=spectre
global 0 VDD
subckt comparator_core inn inp out VDD 0
Mtail (tail bias 0 0) nch_18 w=4u l=180n m=1 nf=2
M0 (out inp tail 0) nch_18 w=2u l=180n m=1 nf=1
M1 (out inn tail 0) nch_18 w=2u l=180n m=1 nf=1
Cload (out 0) capacitor c=15f
Vbias (bias 0) vsource dc=0.8
ends comparator_core
`, { project: "speg_import" }));

  const imported = document.extensions?.importedNetlist as {
    primitiveInstanceCount?: number;
    netCount?: number;
    unsupportedLines?: unknown[];
  } | undefined;
  assert.equal(imported?.primitiveInstanceCount, 5);
  assert.equal(imported?.unsupportedLines?.length, 0);
  assert.ok((imported?.netCount ?? 0) >= 6);
  assert.equal(document.nodes.filter((node) => node.kind === "vsource").length, 1);
  assert.equal(document.nodes.filter((node) => node.kind === "capacitor").length, 1);

  const compiled = compileNetlist(document, "cdl");
  assert.equal(compiled.issues.filter((issue) => issue.severity === "error").length, 0);
  assert.match(compiled.text, /^\.SUBCKT comparator_core inn inp out VDD 0$/m);
  assert.match(compiled.text, /^Mtail tail bias 0 0 nch_18 W=4u L=180n M=1 NF=2$/m);
  assert.match(compiled.text, /^Cload out 0 15f$/m);
});

test("ADC and opamp support devices import from mixed SPICE primitives and macros", () => {
  const document = parseSchematicDocument(importNetlistAsSchematic(`
.SUBCKT adc_top vin clk clkb dout vdd 0 vrefp vrefn vcm bias
D1 vin 0 dio M=2
Q1 cmp bias 0 npn area=2
E1 vcmp 0 vin 0 12
G1 tail 0 bias 0 1m
S1 vin sampled clk clkb swmod
XCDAC top bot ctrl vrefp vrefn vcm cdac_array bits=10 unitCap=1f
XCOMP sampled vcm outp outn clk vdd 0 dynamic_comparator
XSAR clk outp ctrl dout rst 0 sar_logic bits=10
.ENDS adc_top
`, { project: "speg_import" }));

  const kinds = document.nodes.map((node) => node.kind);
  assert.ok(kinds.includes("diode"));
  assert.ok(kinds.includes("npn3"));
  assert.ok(kinds.includes("vcvs"));
  assert.ok(kinds.includes("vccs"));
  assert.ok(kinds.includes("switch4"));
  assert.ok(kinds.includes("cdac_array"));
  assert.ok(kinds.includes("dynamic_comparator"));
  assert.ok(kinds.includes("sar_logic"));

  const imported = document.extensions?.importedNetlist as {
    primitiveInstanceCount?: number;
    unsupportedLines?: unknown[];
  } | undefined;
  assert.equal(imported?.primitiveInstanceCount, 8);
  assert.equal(imported?.unsupportedLines?.length, 0);

  const compiled = compileNetlist(document, "spice");
  assert.equal(compiled.issues.filter((issue) => issue.severity === "error").length, 0);
  assert.match(compiled.text, /^D1 vin 0 dio AREA=1 M=2$/m);
  assert.match(compiled.text, /^Q1 cmp bias 0 npn AREA=2 M=1$/m);
  assert.match(compiled.text, /^E1 vcmp 0 vin 0 12$/m);
  assert.match(compiled.text, /^G1 tail 0 bias 0 1m$/m);
  assert.match(compiled.text, /^S1 vin sampled clk clkb swmod$/m);
  assert.match(compiled.text, /^XCDAC top bot ctrl vrefp vrefn vcm cdac_array BITS=10 UNITCAP=1f$/m);
});

test("multi-subckt Comparator import preserves hierarchy, arity, supplies, and port order", () => {
  const source = `
.subckt dynamic_double_tail_comparator inp inn outp outn vdd vss clk
XLATCH pre_p pre_n outp outn vdd vss clk regenerative_output_latch
XPRE inp inn pre_p pre_n clk vdd vss clocked_input_preamp
.ends dynamic_double_tail_comparator
.subckt clocked_input_preamp inp inn pre_p pre_n clk vdd vss
RINP inp inp_gate 45k
RINN inn inn_gate 45k
MINP pre_p inp_gate tail vss n18 W=1.6u L=500n
MINN pre_n inn_gate tail vss n18 W=1.6u L=500n
.ends clocked_input_preamp
.subckt regenerative_output_latch pre_p pre_n outp outn vdd vss clk
MOUTPP outp latch_p vdd vdd p18 W=1u L=180n
MOUTPN outp latch_p vss vss n18 W=500n L=180n
.ends regenerative_output_latch
`;
  const document = parseSchematicDocument(importNetlistAsSchematic(source, { project: "cmp_hier" }));
  const children = Object.values(hierarchyCellViews(document));
  assert.equal(document.cell, "dynamic_double_tail_comparator");
  assert.equal(children.length, 2);
  assert.equal(document.nodes.filter((node) => node.kind === "subckt7").length, 2);
  assert.ok(document.nodes.every((node) => !node.properties.master || node.properties.hierarchyChildKey));

  const compiled = compileHierarchicalNetlist(document, "spice");
  assert.equal(compiled.issues.length, 0);
  assert.match(compiled.text, /^\.subckt dynamic_double_tail_comparator inp inn outp outn vdd vss clk$/m);
  assert.match(compiled.text, /^XLATCH pre_p pre_n outp outn vdd vss clk regenerative_output_latch$/m);
  assert.match(compiled.text, /^XPRE inp inn pre_p pre_n clk vdd vss clocked_input_preamp$/m);
  assert.match(compiled.text, /^\.subckt clocked_input_preamp inp inn pre_p pre_n clk vdd vss$/m);
  assert.match(compiled.text, /^\.subckt regenerative_output_latch pre_p pre_n outp outn vdd vss clk$/m);
});
