import { buildHierarchicalSchematicExchange } from "./hierarchicalExchange";
import { compileNetlist } from "./netlist";
import type { PdkRequestContract } from "./pdkRegistry";
import type { CadenceSchematicConvertorRequest } from "./schematicConvertor";
import type { SchematicDocument } from "./schematic";

export interface CadenceOaPackageFile {
  path: string;
  role: string;
  cadence_format: "openaccess_oa" | "openaccess_archive" | "routing_report" | "routed_preview" | "cadence_skill" | "cadence_cdl" | "oa_exchange_json" | "analog_studio_json" | "readme";
  mime: string;
  text?: string;
  generated_by_backend?: true;
  note?: string;
}

export interface CadenceOaExportPackage {
  schema: "analog_studio.cadence_oa_handoff_package.v1";
  created_at: string;
  source: {
    project: string;
    library: string;
    cell: string;
    view: string;
    editor_profile: string;
  };
  target: {
    pdk: PdkRequestContract;
    cadence_resource: string;
    output_library: string;
    output_cell: string;
    output_view: "schematic";
  };
  policy: {
    browser_generates_binary_oa: false;
    backend_generates_real_openaccess: true;
    pdk_paths_backend_only: true;
    editable_document_is_source_of_truth: true;
    backend_rebuild_required_after_editor_changes: true;
  };
  editable_round_trip: {
    source_document_role: "analog_studio_hierarchical_editable_source";
    edit_propagation: "compile_current_document_then_submit_to_cadence_schematic_convertor";
    backend_generator: "configured_cadence_backend";
    final_oa_reflects_editor_state: true;
  };
  backend_request: CadenceSchematicConvertorRequest;
  files: CadenceOaPackageFile[];
}

function cleanIdentifier(value: string, fallback: string): string {
  const trimmed = value.trim();
  if (!trimmed) return fallback;
  const replaced = trimmed.replace(/[^A-Za-z0-9_]/g, "_");
  return (/^[A-Za-z_]/.test(replaced) ? replaced : `_${replaced}`).slice(0, 64);
}

function readmeText(document: SchematicDocument, request: CadenceSchematicConvertorRequest): string {
  return [
    "# Analog Studio Cadence OA Handoff",
    "",
    "This package is intended for a configured Cadence Virtuoso/OpenAccess backend.",
    "The browser provides SKILL, CDL, OA-exchange JSON, hierarchy JSON, and the backend request.",
    "The real binary OpenAccess cellview is generated by the Cadence backend, not forged in the browser.",
    "",
    `- target library: ${request.target.output_library}`,
    `- target cell: ${cleanIdentifier(document.cell, "TOP")}`,
    "- target view: schematic",
    `- PDK profile: ${request.target.pdk_profile}`,
    "- expected OA artifact: openaccess/<library>/<cell>/schematic/sch.oa",
    "- expected OA archive: openaccess/cadence_openaccess_library.tar.gz",
    "- expected routing report: reports/cadence_schematic_routing_report.json",
    "- expected routed preview: reports/cadence_routed_schematic_preview.png",
    "",
  ].join("\n");
}

export function buildCadenceOaExportPackage(options: {
  document: SchematicDocument;
  rootDocument: SchematicDocument;
  request: CadenceSchematicConvertorRequest;
  pdk: PdkRequestContract;
  now?: Date;
}): CadenceOaExportPackage {
  const createdAt = (options.now ?? new Date()).toISOString();
  const library = cleanIdentifier(options.document.library || options.document.project, "AI_GEN_LIB");
  const cell = cleanIdentifier(options.document.cell, "TOP");
  const skill = compileNetlist(options.document, "cadence_skill").text;
  const cdl = compileNetlist(options.document, "cdl").text;
  const oaExchange = compileNetlist(options.document, "oa_exchange").text;
  const hierarchy = JSON.stringify(buildHierarchicalSchematicExchange(options.rootDocument), null, 2);
  const requestText = JSON.stringify(options.request, null, 2);
  return {
    schema: "analog_studio.cadence_oa_handoff_package.v1",
    created_at: createdAt,
    source: {
      project: options.document.project,
      library: options.document.library,
      cell: options.document.cell,
      view: options.document.view,
      editor_profile: options.document.editorProfile,
    },
    target: {
      pdk: options.pdk,
      cadence_resource: options.request.resource_id,
      output_library: options.request.target.output_library,
      output_cell: cell,
      output_view: "schematic",
    },
    policy: {
      browser_generates_binary_oa: false,
      backend_generates_real_openaccess: true,
      pdk_paths_backend_only: true,
      editable_document_is_source_of_truth: true,
      backend_rebuild_required_after_editor_changes: true,
    },
    editable_round_trip: {
      source_document_role: "analog_studio_hierarchical_editable_source",
      edit_propagation: "compile_current_document_then_submit_to_cadence_schematic_convertor",
      backend_generator: "configured_cadence_backend",
      final_oa_reflects_editor_state: true,
    },
    backend_request: options.request,
    files: [
      {
        path: `openaccess/${library}/${cell}/schematic/sch.oa`,
        role: "backend OpenAccess schematic cellview",
        cadence_format: "openaccess_oa",
        mime: "application/octet-stream",
        generated_by_backend: true,
        note: "A real sch.oa is a Cadence/OpenAccess database artifact and must be emitted by the configured Cadence backend.",
      },
      {
        path: "openaccess/cadence_openaccess_library.tar.gz",
        role: "backend Cadence OpenAccess library archive",
        cadence_format: "openaccess_archive",
        mime: "application/gzip",
        generated_by_backend: true,
        note: "Archive containing the real OpenAccess library produced by the configured Cadence backend.",
      },
      {
        path: "reports/cadence_schematic_routing_report.json",
        role: "backend schematic routing report",
        cadence_format: "routing_report",
        mime: "application/json",
        generated_by_backend: true,
        note: "Routing report produced by cadence_schematic_convertor after creating real Virtuoso wire figures.",
      },
      {
        path: "reports/cadence_routed_schematic_preview.png",
        role: "backend routed schematic preview",
        cadence_format: "routed_preview",
        mime: "image/png",
        generated_by_backend: true,
        note: "Preview generated from the routed Cadence schematic for visual QA.",
      },
      {
        path: `cadence/scripts/import_${cell}.il`,
        role: "Virtuoso SKILL importer",
        cadence_format: "cadence_skill",
        mime: "text/plain",
        text: skill,
      },
      {
        path: `cadence/netlist/${cell}.cdl`,
        role: "CDL netlist exchange",
        cadence_format: "cadence_cdl",
        mime: "text/plain",
        text: cdl,
      },
      {
        path: `cadence/oa_exchange/${cell}.oa.json`,
        role: "OpenAccess-safe structured exchange",
        cadence_format: "oa_exchange_json",
        mime: "application/json",
        text: oaExchange,
      },
      {
        path: `analog_studio/${cell}.hierarchy.json`,
        role: "Analog Studio hierarchical source of truth",
        cadence_format: "analog_studio_json",
        mime: "application/json",
        text: hierarchy,
      },
      {
        path: `analog_studio/${cell}.editable-roundtrip.json`,
        role: "editable source to OpenAccess rebuild contract",
        cadence_format: "analog_studio_json",
        mime: "application/json",
        text: JSON.stringify({
          schema: "analog_studio.cadence_editable_roundtrip.v1",
          source_document: `analog_studio/${cell}.hierarchy.json`,
          backend_request: `cadence/request/${options.request.job_id}.cadence-convertor-request.json`,
          backend_generator: "configured_cadence_backend",
          final_openaccess_artifact: `openaccess/${library}/${cell}/schematic/sch.oa`,
          rule: "Any editor-side change must be saved into the hierarchy JSON and submitted through the backend request before claiming the OA reflects the visible schematic.",
        }, null, 2),
      },
      {
        path: `cadence/request/${options.request.job_id}.cadence-convertor-request.json`,
        role: "Cadence backend job request",
        cadence_format: "analog_studio_json",
        mime: "application/json",
        text: requestText,
      },
      {
        path: "README.md",
        role: "handoff instructions",
        cadence_format: "readme",
        mime: "text/markdown",
        text: readmeText(options.document, options.request),
      },
    ],
  };
}
